"""Generate baseline-XGBoost error-analysis figures and machine-readable results."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import joblib
import numpy as np
import pandas as pd

from src import CLASS_NAMES, CONFIGS_DIR, FIGURES_DIR, MODELS_DIR, RANDOM_STATE, RESULTS_DIR
from src.data import load_split
from src.evaluation import (
    aggregate_fatal_shap_by_source,
    class_pair_overlaps,
    evaluate_predictions,
)
from src.models import load_config
from src.visualization import (
    compute_tree_shap,
    is_categorical_distribution,
    save_confusion_matrix,
    save_fatal_precision_recall_curve,
    save_fatal_shap,
    save_fatal_threshold_tradeoff,
    save_feature_distribution_by_class,
    save_global_shap_summary,
    save_normalized_confusion_matrix,
)


def _slug(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "_", value.lower()).strip("_")


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _source_values(X: pd.DataFrame, source_feature: str) -> pd.Series:
    if source_feature != "Hour_of_Day":
        if source_feature not in X.columns:
            raise KeyError(f"source feature is unavailable in the test data: {source_feature}")
        return X[source_feature].rename(source_feature)
    angle = np.mod(np.arctan2(X["hour_sin"], X["hour_cos"]), 2 * np.pi)
    hour = np.rint(angle * 24 / (2 * np.pi)).astype(int) % 24
    return pd.Series(hour, index=X.index, name=source_feature)


def _generated_markdown(result: dict, overlap_frame: pd.DataFrame) -> str:
    metrics = result["test_metrics"]
    pr = result["fatal_precision_recall"]
    lines = [
        "# Generated error-analysis summary",
        "",
        "_Generated by `scripts/generate_error_analysis.py`; the curated modeling report is not modified._",
        "",
        "## Downsampled-baseline XGBoost held-out metrics",
        "",
        "| Metric | Value |",
        "| --- | ---: |",
        f"| Accuracy | {metrics['accuracy']:.3f} |",
        f"| Macro F1 | {metrics['macro_f1']:.3f} |",
        f"| Fatal precision | {metrics['per_class_precision'][0]:.3f} |",
        f"| Fatal recall | {metrics['per_class_recall'][0]:.3f} |",
        f"| Fatal F1 | {metrics['per_class_f1'][0]:.3f} |",
        f"| Fatal average precision | {pr['average_precision']:.3f} |",
        "",
        "## True-class feature overlap",
        "",
        overlap_frame.to_markdown(index=False, floatfmt=".3f"),
        "",
        "Overlap is probability-mass intersection: 1 indicates identical distributions; 0 indicates no shared mass.",
        "",
        "## Figures",
        "",
        "- [Confusion matrix](../figures/confusion_matrix.png)",
        "- [Normalized confusion matrix](../figures/confusion_matrix_normalized.png)",
        "- [Fatal precision–recall curve](../figures/fatal_precision_recall.png)",
        "- [Fatal threshold tradeoff](../figures/fatal_threshold_tradeoff.png)",
        "- [Global SHAP](../figures/shap_global.png)",
        "- [Fatal-specific SHAP](../figures/shap_fatal.png)",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    argparse.ArgumentParser(description=__doc__).parse_args()
    model_path = MODELS_DIR / "baseline_xgb.joblib"
    threshold_path = CONFIGS_DIR / "baseline_fatal_threshold.json"
    tradeoff_path = RESULTS_DIR / "baseline_threshold_results.csv"
    required = [model_path, threshold_path, tradeoff_path]
    missing = [str(path.relative_to(Path.cwd())) for path in required if not path.exists()]
    threshold_config = json.loads(threshold_path.read_text()) if threshold_path.exists() else {}
    if missing or threshold_config.get("status") != "ready":
        raise FileNotFoundError(
            "Complete `make train-baseline` first; missing or stale: "
            f"{missing or ['configs/baseline_fatal_threshold.json']}"
        )
    if threshold_config.get("model_artifact") != "models/baseline_xgb.joblib":
        raise ValueError("the frozen Fatal threshold is not associated with baseline_xgb.joblib")

    model = joblib.load(model_path)
    _, X_test, _, y_test = load_split()
    probabilities = np.asarray(model.predict_proba(X_test), dtype=float)
    predictions = np.asarray(model.predict(X_test), dtype=int)
    metrics = evaluate_predictions(y_test, predictions, load_config("baseline_xgb")["name"])

    FIGURES_DIR.mkdir(parents=True, exist_ok=True)
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    distribution_dir = FIGURES_DIR / "feature_distributions"
    distribution_dir.mkdir(parents=True, exist_ok=True)
    for stale_plot in distribution_dir.glob("*.png"):
        stale_plot.unlink()

    save_confusion_matrix(
        metrics["confusion_matrix"], metrics["name"], FIGURES_DIR / "confusion_matrix.png"
    )
    save_normalized_confusion_matrix(
        metrics["confusion_matrix"],
        metrics["name"],
        FIGURES_DIR / "confusion_matrix_normalized.png",
    )
    threshold = float(threshold_config["threshold"])
    pr_metrics = save_fatal_precision_recall_curve(
        y_test,
        probabilities[:, 0],
        threshold,
        FIGURES_DIR / "fatal_precision_recall.png",
    )
    threshold_rows = pd.read_csv(tradeoff_path).to_dict(orient="records")
    save_fatal_threshold_tradeoff(
        threshold_rows, threshold, FIGURES_DIR / "fatal_threshold_tradeoff.png"
    )

    X_shap, shap_values = compute_tree_shap(model, X_test)
    save_global_shap_summary(
        shap_values, list(X_shap.columns), FIGURES_DIR / "shap_global.png"
    )
    save_fatal_shap(shap_values, X_shap, FIGURES_DIR / "shap_fatal.png")
    ranking = aggregate_fatal_shap_by_source(
        model.named_steps["preprocessor"], list(X_shap.columns), shap_values[:, :, 0]
    )

    feature_results = []
    overlap_rows = []
    for rank, importance in enumerate(ranking[:5], start=1):
        feature = importance["source_feature"]
        values = _source_values(X_test, feature)
        categorical = is_categorical_distribution(values, feature)
        overlaps = class_pair_overlaps(values, y_test, categorical=categorical)
        fatal_serious = next(
            row["overlap"]
            for row in overlaps
            if {row["class_a"], row["class_b"]} == {"Fatal", "Serious"}
        )
        filename = f"{_slug(feature)}.png"
        save_feature_distribution_by_class(
            values,
            y_test,
            feature,
            fatal_serious,
            distribution_dir / filename,
        )
        feature_result = {
            "rank": rank,
            **importance,
            "distribution_kind": "categorical" if categorical else "numeric",
            "figure": f"reports/figures/feature_distributions/{filename}",
            "pairwise_overlaps": overlaps,
        }
        feature_results.append(feature_result)
        for row in overlaps:
            overlap_rows.append(
                {
                    "rank": rank,
                    "feature": feature,
                    "mean_abs_fatal_shap": importance["mean_abs_fatal_shap"],
                    "distribution_kind": feature_result["distribution_kind"],
                    "class_a": row["class_a"],
                    "class_b": row["class_b"],
                    "overlap": row["overlap"],
                    "figure": feature_result["figure"],
                }
            )

    result = {
        "model": {
            "name": metrics["name"],
            "artifact": "models/baseline_xgb.joblib",
            "sha256": _sha256(model_path),
        },
        "evaluation": {
            "split": "frozen untouched stratified 20% test split",
            "rows": int(len(y_test)),
            "random_state": RANDOM_STATE,
            "class_order": CLASS_NAMES,
            "class_counts": {
                class_name: int(np.sum(y_test == index))
                for index, class_name in enumerate(CLASS_NAMES)
            },
            "confusion_matrix_policy": "downsampled-baseline XGB multiclass predict/argmax",
        },
        "test_metrics": metrics,
        "fatal_threshold": threshold_config,
        "fatal_precision_recall": pr_metrics,
        "threshold_tradeoff_source": (
            "reports/results/baseline_threshold_results.csv (training OOF only)"
        ),
        "shap": {
            "sample_rows": int(len(X_shap)),
            "random_state": RANDOM_STATE,
            "source_feature_ranking": ranking,
        },
        "feature_distributions": feature_results,
    }
    overlap_frame = pd.DataFrame(overlap_rows)
    (RESULTS_DIR / "error_analysis.json").write_text(json.dumps(result, indent=2) + "\n")
    overlap_frame.to_csv(RESULTS_DIR / "feature_class_overlap.csv", index=False)
    (RESULTS_DIR / "error_analysis_generated.md").write_text(
        _generated_markdown(result, overlap_frame)
    )
    print("[done] updated error-analysis figures and reports/results/error_analysis.*")
    print("[preserved] reports/modeling_report.md was not modified")
    return 0


if __name__ == "__main__":
    sys.exit(main())
